### ISSUE TITLE
Design a good looking login page.

### ISSUE THREAD

**Issue by volley-freak** [Volley-Freak/gotLost#19]
You can grab the html file from the repository. then you just need to add some CSS on it.

**Comment by Volley-Freak** [comment]
Hey @underscoremissa just consider the theme of the website while designing. Thanks!

**Comment by underscoremissa** [comment]
> Hey @underscoremissa just consider the theme of the website while designing. Thanks!

There is a contact us page which has a form, shall I add css to it. Or make one  form SignIn page?

Also, About Us page is not linked to the About_us.html page.

**Comment by underscoremissa** [comment]
> Hey @underscoremissa just consider the theme of the website while designing. Thanks!

PRed the same.

There are additional issues with the project, like the index page is not linked with the source. Hope to work more with you.
Thankyou.
