### ISSUE TITLE
Navbar of other pages except index are not sticky and there is no graw effect in the achor tags.

### ISSUE THREAD

**Issue by mr-palindrome** [Volley-Freak/gotLost#34]
I will make the navbar of all other pages sticky and add the grow effect in all other pages.

**Comment by pranjal-arora** [comment]
Hey! I would like to take up this issue!

**Comment by Volley-Freak** [comment]
Hello, 
@BirajGupta @pranjal-arora thank you for stepping ahead, as this issue has already been assigned you can find some other issues and work on them.
