### ISSUE TITLE
Add Contributors section in README.md 

### ISSUE THREAD

**Issue by volley-freak** [Volley-Freak/gotLost#37]
#### Add Contributors section in README.md which will showcase all the valuable contributors. You can take help from other repositories.
An example screenshot:
![Screenshot from 2021-10-18 01-32-53](https://user-images.githubusercontent.com/85556562/137643205-a817a642-d48d-40db-949d-20b78a76043a.png)
.

**Comment by AbogeJr** [comment]
Hey. I'd love to work on this! May I?

**Comment by Volley-Freak** [comment]
> Hey. I'd love to work on this! May I?

Yeah sure go for it!!

**Comment by AbogeJr** [comment]
Thanks

**Comment by Manishgupta200** [comment]
I would like to work on it. please, assign it to me.
can you please label me as a hacktoberfest-accepted after successfully accepting a pull request from me?

**Comment by Manishgupta200** [comment]
ok, thanks for assigned

**Comment by govind030303** [comment]
May I get this issue assigned ??

**Comment by Volley-Freak** [comment]
@govind030303 as this issue is resolved you can search some other issues on website.
Thank you!
